import React from 'react';
import {
  Banknote,
  BookOpen,
  Briefcase,
  Calendar,
  Car,
  CheckCircle2,
  Coins,
  CreditCard,
  FileBarChart,
  Gift,
  GraduationCap,
  Heart,
  HeartHandshake,
  HeartPulse,
  HelpCircle,
  Home,
  Landmark,
  Layers,
  MessageCircleHeart,
  MoreHorizontal,
  PiggyBank,
  Plane,
  PlusCircle,
  Repeat,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Tag,
  Target,
  TrendingUp,
  Utensils,
  Wallet,
  Wrench,
  Zap,
} from 'lucide-react';

const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  Wallet,
  Banknote,
  Landmark,
  Smartphone,
  CreditCard,
  Briefcase,
  Gift,
  TrendingUp,
  PlusCircle,
  Utensils,
  Zap,
  Home,
  Car,
  GraduationCap,
  HeartPulse,
  Sparkles,
  MoreHorizontal,
  Tag,
  Target,
  ShieldCheck,
  Plane,
  PiggyBank,
  Coins,
  ShoppingBag,
  Calendar,
  Wrench,
  MessageCircleHeart,
  BookOpen,
  FileBarChart,
  HelpCircle,
  Heart,
  HeartHandshake,
  Repeat,
  Layers,
  CheckCircle2,
};

export const AVAILABLE_ICON_NAMES = [
  'Wallet',
  'Banknote',
  'Landmark',
  'Smartphone',
  'Briefcase',
  'Gift',
  'TrendingUp',
  'Utensils',
  'Zap',
  'Home',
  'Car',
  'GraduationCap',
  'HeartPulse',
  'Sparkles',
  'ShoppingBag',
  'Target',
  'ShieldCheck',
  'Plane',
  'PiggyBank',
  'Coins',
  'Heart',
  'Wrench',
  'Tag',
];

export const PALETTE_COLORS = [
  { label: 'Dark Green', value: '#2A4D3E' },
  { label: 'Mustard Gold', value: '#D4A359' },
  { label: 'Sage', value: '#84A59D' },
  { label: 'Dusty Rose', value: '#D88C9A' },
  { label: 'Muted Blue', value: '#6B9080' },
  { label: 'Teal', value: '#457B9D' },
  { label: 'Warm Orange', value: '#E07A5F' },
  { label: 'Lavender', value: '#9D8189' },
];

export function IconRenderer({
  name,
  className = 'w-5 h-5',
}: {
  name?: string;
  className?: string;
}) {
  const IconComponent = (name && ICON_MAP[name]) || Tag;
  return <IconComponent className={className} />;
}
